version: '3'

networks:
  nginx-phpfpm-mysql:

services:

  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm-service
      - mysql-service
    networks:
      - nginx-phpfpm-mysql

  #phpfpm
  phpfpm-service:
    image: bitnami/php-fpm:latest
    networks:
      - nginx-phpfpm-mysql
    volumes:
      - ./public_php:/public_php


  #mysql
  mysql-service:
    image: mysql:5.7.30
    container_name: MySqlDatabase
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
