version: '3'

networks:
  nginxphpmysql:

services:

  #nginx
  web:
    image: nginx:1.17
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d/
    networks:
      - nginxphpmysql

  #phpfpm
  php:
    image: php:8.1-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - nginxphpmysql

  #mysql
  mysql-service:
    image: mysql:5.7.30
    container_name: MySqlDatabase
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - nginxphpmysql
